# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Poland"
    open-pull-requests-limit: 3
    assignees:
    - "wkobiela"
    versioning-strategy: increase-if-necessary

  # Github Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Poland"
    open-pull-requests-limit: 3
    assignees:
      - "wkobiela"