name: Pylint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v5

    - name: Setup python
      uses: actions/setup-python@v5
      with:
          python-version: '3.12'
          cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Analysing the code with pylint
      run: |
        pylint $(find . -name "*.py" | xargs) --rcfile=.pylintrc